Adding doc/requirements.txt to pull in sphinx_rtd_theme to remove
ThemeError: sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)

Theme error:
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)

error when publishing on ReadTheDocs site.